# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.0.46
_src_path: gh:clearskies-py/clearskies-module-template
author_email: tom.nijboer@cimpress.com
author_name: Tom Nijboer
create_backends: false
create_columns: false
create_configs: false
create_endpoints: false
create_models: false
docs_modules_location: modules
module_display_name: Clearskies MCP
module_name: mcp
site_base_url: https://clearskies.info
