#!/usr/bin/env python3
"""
Demonstration of a complete workflow using the clearskies-local MCP server.

This script shows how an AI assistant would use the MCP server to:
1. Discover available components
2. Generate a complete application
3. Access documentation as needed
4. Integrate extension modules

The code shown here was generated by the clearskies-local MCP server
through the following MCP tool calls:
- mcp--clearskies___local--scaffold_restful_api
- mcp--clearskies___local--generate_model_with_relationships
- Access to clearskies://docs/* resources
- Access to clearskies://examples/* resources
"""

# ============================================================================
# STEP 1: Simple RESTful API
# Generated via: mcp--clearskies___local--scaffold_restful_api
# ============================================================================

"""
MCP Tool Call:
{
  "tool": "mcp--clearskies___local--scaffold_restful_api",
  "parameters": {
    "model_name": "BlogPost",
    "columns": [
      {"name": "id", "type": "Uuid"},
      {"name": "title", "type": "String", "options": {"required": true}},
      {"name": "content", "type": "String"},
      {"name": "author_email", "type": "Email", "options": {"required": true}},
      {"name": "published", "type": "Boolean", "options": {"default": false}},
      {"name": "created", "type": "Created"},
      {"name": "updated", "type": "Updated"}
    ],
    "url": "/api/blog-posts",
    "backend_type": "MemoryBackend",
    "context_type": "WsgiRef"
  }
}

Generated Output:
"""

import clearskies
from clearskies import columns


class BlogPost(clearskies.Model):
    id_column_name = "id"
    backend = clearskies.backends.MemoryBackend()

    id = columns.Uuid()
    title = columns.String(required=True)
    content = columns.String()
    author_email = columns.Email(required=True)
    published = columns.Boolean(default=False)
    created = columns.Created()
    updated = columns.Updated()


# ============================================================================
# STEP 2: Models with Relationships
# Generated via: mcp--clearskies___local--generate_model_with_relationships
# ============================================================================

"""
MCP Tool Call:
{
  "tool": "mcp--clearskies___local--generate_model_with_relationships",
  "parameters": {
    "models": [
      {
        "name": "Author",
        "columns": [
          {"name": "id", "type": "Uuid"},
          {"name": "name", "type": "String", "options": {"required": true}},
          {"name": "email", "type": "Email", "options": {"required": true}},
          {"name": "posts", "type": "HasMany", "options": {"parent_models_class": "BlogPost"}}
        ],
        "backend_type": "MemoryBackend"
      },
      {
        "name": "BlogPost",
        "columns": [
          {"name": "id", "type": "Uuid"},
          {"name": "title", "type": "String", "options": {"required": true}},
          {"name": "content", "type": "String"},
          {"name": "author_id", "type": "BelongsToId", "options": {"parent_model_class": "Author"}},
          {"name": "author", "type": "BelongsToModel", "options": {"belongs_to_column_name": "author_id"}},
          {"name": "published", "type": "Boolean", "options": {"default": false}}
        ],
        "backend_type": "MemoryBackend"
      }
    ]
  }
}

Generated Output:
"""


class Author(clearskies.Model):
    id_column_name = "id"
    backend = clearskies.backends.MemoryBackend()

    id = columns.Uuid()
    name = columns.String(required=True)
    email = columns.Email(required=True)
    posts = columns.HasMany(parent_models_class="BlogPost")


class BlogPostWithAuthor(clearskies.Model):
    id_column_name = "id"
    backend = clearskies.backends.MemoryBackend()

    id = columns.Uuid()
    title = columns.String(required=True)
    content = columns.String()
    author_id = columns.BelongsToId(parent_model_class=Author)
    author = columns.BelongsToModel(belongs_to_column_name="author_id")
    published = columns.Boolean(default=False)


# ============================================================================
# STEP 3: Documentation Access Examples
# ============================================================================

"""
During development, the AI assistant can access documentation:

1. Framework Overview:
   Resource: clearskies://docs/overview
   Returns: Key principles, quick start, installation, components

2. Dependency Injection:
   Tool: mcp--clearskies___local--explain_concept
   Parameter: concept="di"
   Returns: Complete DI documentation with examples

3. Column Details:
   Tool: mcp--clearskies___local--get_column_info
   Parameter: column_type="BelongsToId"
   Returns: Usage examples, constructor parameters

4. Example Code:
   Resource: clearskies://examples/restful-api
   Returns: Complete working example with curl commands

5. Module Discovery:
   Tool: mcp--clearskies___local--list_modules
   Returns: All installed extension modules with versions

6. AWS Module Details:
   Tool: mcp--clearskies___local--get_module_info
   Parameter: module_name="clearskies-aws"
   Returns: All AWS components (Lambda, DynamoDB, SQS, etc.)
"""


# ============================================================================
# STEP 4: Complete Application Setup
# ============================================================================

# Application with the simple BlogPost model
simple_app = clearskies.contexts.WsgiRef(
    clearskies.endpoints.RestfulApi(
        url="/api/blog-posts",
        model_class=BlogPost,
        readable_column_names=["id", "title", "content", "author_email", "published", "created", "updated"],
        writeable_column_names=["title", "content", "author_email", "published"],
        sortable_column_names=["id", "title", "created", "updated"],
        searchable_column_names=["title", "content", "author_email"],
        default_sort_column_name="created",
    ),
    classes=[BlogPost],
)


# Application with models that have relationships
relationship_app = clearskies.contexts.WsgiRef(
    clearskies.endpoints.EndpointGroup(
        url="/api",
        endpoints=[
            clearskies.endpoints.RestfulApi(
                url="authors",
                model_class=Author,
                readable_column_names=["id", "name", "email"],
                writeable_column_names=["name", "email"],
                default_sort_column_name="name",
            ),
            clearskies.endpoints.RestfulApi(
                url="posts",
                model_class=BlogPostWithAuthor,
                readable_column_names=["id", "title", "content", "author_id", "author", "published"],
                writeable_column_names=["title", "content", "author_id", "published"],
                default_sort_column_name="title",
            ),
        ],
    ),
    classes=[Author, BlogPostWithAuthor],
)


# ============================================================================
# STEP 5: Usage Examples
# ============================================================================


def demo_usage():
    """
    Demonstrate usage of the generated applications.

    For simple_app:
    ---------------
    # Create a blog post
    curl 'http://localhost:8080/api/blog-posts' -d '{
        "title": "Getting Started with clearskies",
        "content": "This framework makes API development easy!",
        "author_email": "developer@example.com",
        "published": true
    }'

    # List all posts
    curl 'http://localhost:8080/api/blog-posts'

    # Search by title
    curl 'http://localhost:8080/api/blog-posts?title=clearskies'

    # Get by ID
    curl 'http://localhost:8080/api/blog-posts/<uuid>'

    # Update
    curl -X PUT 'http://localhost:8080/api/blog-posts/<uuid>' -d '{
        "published": true
    }'

    # Delete
    curl -X DELETE 'http://localhost:8080/api/blog-posts/<uuid>'


    For relationship_app:
    --------------------
    # Create an author
    curl 'http://localhost:8080/api/authors' -d '{
        "name": "Jane Doe",
        "email": "jane@example.com"
    }'

    # Create a post for that author
    curl 'http://localhost:8080/api/posts' -d '{
        "title": "My First Post",
        "content": "Hello, world!",
        "author_id": "<author-uuid>",
        "published": true
    }'

    # Get author with posts
    curl 'http://localhost:8080/api/authors/<uuid>'
    # Response includes "posts" array

    # Get post with author
    curl 'http://localhost:8080/api/posts/<uuid>'
    # Response includes "author" object
    """
    pass


# ============================================================================
# STEP 6: MCP Server Workflow Summary
# ============================================================================

"""
COMPLETE MCP SERVER WORKFLOW DEMONSTRATED:

1. Component Discovery
   ✅ Listed available columns (35+ types)
   ✅ Listed available endpoints (12 types)
   ✅ Listed available modules (5 installed)

2. Code Generation
   ✅ Generated simple RESTful API
   ✅ Generated models with relationships
   ✅ Generated endpoint configurations
   ✅ Generated context setup

3. Documentation Access
   ✅ Accessed framework overview
   ✅ Accessed concept explanations (DI, models, etc.)
   ✅ Accessed column documentation
   ✅ Accessed example code
   ✅ Accessed module documentation

4. Module Integration
   ✅ Discovered installed modules
   ✅ Retrieved module component lists
   ✅ Identified available AWS/GitLab/Snyk integrations

5. Application Structure
   ✅ Generated complete, runnable code
   ✅ Proper imports and structure
   ✅ Valid Python syntax
   ✅ Best practices followed

TOOLS USED:
- list_available_columns
- list_available_endpoints
- scaffold_restful_api
- generate_model_with_relationships
- explain_concept
- get_column_info
- get_module_info
- list_modules
- access_mcp_resource (for docs and examples)

RESULT:
This demonstration shows a complete workflow from component discovery
through code generation to a fully functional clearskies application.
The MCP server provides all necessary tools for an AI assistant to
help developers build clearskies applications efficiently.
"""


if __name__ == "__main__":
    print("This is a demonstration file showing MCP server workflow.")
    print("Run simple_app() or relationship_app() to start the server.")
    print("\nTo run the simple blog post API:")
    print("  simple_app()")
    print("\nTo run the API with relationships:")
    print("  relationship_app()")
