"""
MCP Resources for clearskies documentation and examples.

This module contains resource functions that provide documentation content.
"""

from .docs import (
    docs_advanced_columns,
    docs_advanced_queries,
    docs_async,
    docs_auth_flow,
    docs_authentication,
    docs_authorization,
    docs_backend_cursor,
    # Phase 6.1: Backend Foundations
    docs_backend_memory,
    docs_backends,
    docs_best_practices,
    docs_caching,
    # Phase 6.4: Reference Material
    docs_column_reference,
    docs_columns,
    docs_configuration,
    docs_contexts,
    docs_cursors,
    docs_di,
    # Phase 6.2: Framework Internals
    docs_di_advanced,
    docs_endpoint_groups,
    docs_endpoint_reference,
    docs_endpoints,
    docs_error_handling,
    docs_exceptions,
    docs_input_handling,
    docs_input_output,
    docs_logging,
    docs_migrations,
    docs_model_lifecycle,
    docs_models,
    docs_overview,
    docs_patterns,
    docs_performance,
    docs_queries,
    docs_query_execution,
    docs_responses,
    docs_routing,
    docs_save_lifecycle,
    docs_secrets_backend,
    docs_state_machine_advanced,
    docs_testing,
    docs_transactions,
    # Phase 6.3: Developer Experience
    docs_troubleshooting,
    docs_validators,
)
from .examples import (
    example_advanced_queries,
    example_api_backend,
    example_audit_trail,
    example_authentication,
    example_authorization,
    example_cli_app,
    example_configuration,
    example_endpoint_group,
    example_error_handling,
    example_hierarchical_data,
    example_migrations,
    example_pivot_data,
    example_relationships,
    example_restful_api,
    example_secrets_backend,
    example_state_machine_advanced,
    example_testing,
)
from .modules import (
    module_akeyless,
    module_aws,
    module_cortex,
    module_gitlab,
    module_graphql,
    module_snyk,
    modules_overview,
)
from .style import (
    style_docstrings,
)

__all__ = [
    # Documentation resources
    "docs_overview",
    "docs_models",
    "docs_endpoints",
    "docs_columns",
    "docs_backends",
    "docs_contexts",
    "docs_di",
    "docs_authentication",
    "docs_save_lifecycle",
    "docs_queries",
    "docs_validators",
    "docs_testing",
    "docs_authorization",
    "docs_error_handling",
    "docs_input_handling",
    "docs_endpoint_groups",
    "docs_routing",
    "docs_responses",
    "docs_migrations",
    "docs_advanced_columns",
    "docs_advanced_queries",
    "docs_configuration",
    "docs_logging",
    "docs_caching",
    "docs_async",
    "docs_state_machine_advanced",
    "docs_secrets_backend",
    # Phase 6.1: Backend Foundations
    "docs_backend_memory",
    "docs_backend_cursor",
    "docs_cursors",
    "docs_transactions",
    # Phase 6.2: Framework Internals
    "docs_di_advanced",
    "docs_query_execution",
    "docs_model_lifecycle",
    "docs_input_output",
    # Phase 6.3: Developer Experience
    "docs_troubleshooting",
    "docs_best_practices",
    "docs_exceptions",
    "docs_auth_flow",
    # Phase 6.4: Reference Material
    "docs_column_reference",
    "docs_endpoint_reference",
    "docs_performance",
    "docs_patterns",
    # Example resources
    "example_restful_api",
    "example_relationships",
    "example_authentication",
    "example_cli_app",
    "example_api_backend",
    "example_testing",
    "example_authorization",
    "example_error_handling",
    "example_endpoint_group",
    "example_migrations",
    "example_hierarchical_data",
    "example_audit_trail",
    "example_pivot_data",
    "example_advanced_queries",
    "example_configuration",
    "example_state_machine_advanced",
    "example_secrets_backend",
    # Module resources
    "modules_overview",
    "module_aws",
    "module_graphql",
    "module_gitlab",
    "module_cortex",
    "module_snyk",
    "module_akeyless",
    # Style resources
    "style_docstrings",
]
